services:
  postgres:
    image: postgres:16-alpine
    container_name: expense_tracker_postgres
    environment:
      POSTGRES_DB: expense_tracker
      POSTGRES_USER: eduardo
      POSTGRES_PASSWORD: eduardo123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: