spring.application.name=expense-tracker
spring.jpa.open-in-view=true
server.port=${PORT:8080}
spring.profiles.active=dev
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.engine.jdbc.env.internal=DEBUG
# desativa o gerenciamento automatico do docker
spring.docker.compose.enabled=false