spring.application.name=expense-tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker
spring.datasource.username=postgres
spring.datasource.password=minhasenha

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true