spring.application.name=expense-tracker
spring.jpa.open-in-view=true
server.port=${PORT:8080}
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.engine.jdbc.env.internal=DEBUG
api.security.token.secret=minha-chave-super-secreta-123